# Generated by Django 5.2.3 on 2025-07-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('pan_no', models.CharField(blank=True, max_length=9, null=True)),
                ('address', models.CharField(blank=True, max_length=140, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('mrp', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=9, null=True)),
                ('free_products', models.IntegerField(blank=True, default=0, null=True)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='product.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
