# Generated by Django 5.2.3 on 2025-07-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='free_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='net_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
